### ISSUE TITLE
Upload CSV needs to check file type and format and display error message if not csv

### ISSUE THREAD

**Issue by justinyh** [Drakran/TouchPoint#40]
As stated, if I upload a file that is not a CSV, there are no error messages telling me what happened. Additionally, we need to ensure that the csv file follows our format or throw an error.

**Comment by hnguyen0** [comment]
Backend will throw a 400 status code with the message "The csv file does not have the correct format." if it can't parse it
Lemme know if there's anything else in the backend to be done
It would be nice UI (but not required) if we could also display like a sample CSV or just some sort of correct formatting
