### ISSUE TITLE
Upload CSV is appending to periods array as opposed to updating

### ISSUE THREAD

**Issue by justinyh** [Drakran/TouchPoint#42]
When I upload a new CSV, it is appending to the periods array in the database as opposed to updating the array. Not sure what root cause is.

**Comment by Drakran** [comment]
Just checking are you trying to upload a csv and update a period thats already in the database? I believe I asked him if anyone would do that and I believe he said no unless we're talking about something else.

**Comment by Drakran** [comment]
Well either way have to either fix it, or block it so yeah.

**Comment by Drakran** [comment]
It overrides it I think we can close this
